services:
  jellytags:
    build: .
    container_name: jellytags
    restart: unless-stopped
    ports:
      - "8181:80"
    environment:
      - VITE_JELLYFIN_URL=http://your-jellyfin-server:8096
      - VITE_JELLYFIN_TOKEN=your-api-token # MUST HAVE ADMIN PRIVILEGES
    # Optionally mount a local env file
    # env_file:
    #   - .env
